# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sWQBkFLob4_rVxesH9lw1m3Obdh2jc_V
"""

# importing required libaries
import pandas as pd
import numpy as np
from scipy import stats

import matplotlib.pyplot as plt
import seaborn as sns

import warnings
warnings.filterwarnings("ignore")

"""# Question 1.

Your task is to clean and transform the dataset to prepare it for analysis.
"""

registered_users = pd.read_csv('Assignment/RegisteredUsers.csv')
registered_users.head()

registered_users['Password'] = registered_users['Password'].str.strip() # Remove legacy spaces from passwords
registered_users.drop_duplicates(inplace=True) # Drop duplicates

# Assume data updating errors refer to missing values, so I decided to drop rows with missing values
registered_users.dropna(inplace=True)

registered_users.head()

"""# Checking
1. No missing values in registered_users dataframe.
2. The data is in the right data-type.

The data is now ready for analysis

# Question 2

Use the Donations.csv dataset, which contains information about donations made onto a charity website on a particular day. Your task is to use this data to infer information about all days.

a)	Calculate a 95% confidence interval for the mean money donated in donations.	[4 marks]

b)	Determine the proportion of website visits that would last longer than 400 seconds.		[2 marks]
"""

donations = pd.read_csv('Assignment/Donations.csv')
donations.head()

# Calculate sample mean and standard deviation
mean_donation = donations['Donation Amount'].mean()
std_dev_donation = donations['Donation Amount'].std(ddof=1)  # ddof=1 for sample standard deviation

n = len(donations) # Calculate the sample size

# Calculate the Z-score for a 95% confidence interval
z_score = stats.norm.ppf(0.975)  # 95% confidence level, two-tailed

margin_of_error = z_score * (std_dev_donation / np.sqrt(n)) # Calculate the margin of error

confidence_interval = (mean_donation - margin_of_error, mean_donation + margin_of_error) # Calculate the confidence interval

print(f"a) 95% Confidence Interval for the mean money donated in donations falls within range of: {confidence_interval[0]} and {confidence_interval[1]}.")

# Calculate proportion of visits lasting longer than 400 seconds
proportion_longer_than_400 = (donations['Time Spent on Website (Seconds)'] > 400).mean()

print(f"b) Proportion of website visits lasting longer than 400 seconds: {proportion_longer_than_400}.")

"""# Question 3

Use the WorkplaceIncidents.csv dataset, which contains information about events where employees were harmed (or nearly harmed) at work in a company.

You work at this company, and a senior colleague of yours claims that “these workplace incidents are costing us €2000 on average!”. (You ask him “Do the misses, that we still have to fill out, count?”, and he responds: “Obviously not”.) You decide to fact-check his claim.

Carry out a relevant hypothesis test (include all steps), to the 5% level of significance, for this scenario.	[6 marks]

(Your hypothesis should include a conclusion, which should be written in words reflecting the scenario.)

"""

workplace_incidents = pd.read_csv('Assignment/WorkplaceIncidents.csv')
workplace_incidents.head()

average_cost = workplace_incidents['Incident Cost'].mean() # Calculate the average cost of workplace incidents

# Perform the hypothesis test
# Null hypothesis: The average cost of workplace incidents is €2000.
# Alternative hypothesis: The average cost of workplace incidents is not €2000.
alpha = 0.05
t_statistic, p_value = stats.ttest_1samp(workplace_incidents['Incident Cost'].dropna(), 2000, nan_policy='omit')

print("Average Cost of Workplace Incidents:", average_cost)
print("t-statistic:", t_statistic)
print("p-value:", p_value)

# Make a decision
if p_value < alpha:
    print("\nReject the null hypothesis. The average cost of workplace incidents is not €2000.")
else:
    print("\nFail to reject the null hypothesis. The average cost of workplace incidents is €2000.")

"""### Findings

Based on the hypothesis test results:

Since the p-value (0.20998) is greater than the significance level (α = 0.05), we fail to reject the null hypothesis. Therefore, we do not have enough evidence to conclude that the average cost of workplace incidents is different from €2000.

Conclusion:
Based on the analysis, we cannot reject the claim made by the senior colleague that the average cost of workplace incidents is €2000.

# Question 4

You are a literary researcher, and are going to present your findings on the topic of how literary works are performing compared to how they are published.
"""

literary_works = pd.read_csv('Assignment/LiteraryWorks.csv')
literary_works.head()

"""### Create a bar chart comparing publishing type and average rating"""

avg_rating_by_publishing_type = literary_works.groupby('Publishing Type')['Rating (stars)'].mean().sort_values()

plt.figure(figsize=(10, 6))
sns.barplot(x=avg_rating_by_publishing_type.index, y=avg_rating_by_publishing_type.values, palette='viridis')

plt.xlabel('Publishing Type')
plt.ylabel('Average Rating')
plt.title('Average Rating of Literary Works by Publishing Type')
plt.plot()

avg_rating_by_publishing_type

"""### Findings
Interestingly, there is a marginal difference in the average ratings between works published via traditional trade channels (3.75 stars) and those self-published (3.30 stars), suggesting that the publishing method might have a subtle influence on the reception of literary works.

# Question 5

She wants you to investigate if there is a relationship (and if so, what kind of relationship) between employees’ salaries and how long they have worked at the company.
"""

employee_details = pd.read_csv('Assignment/EmployeeDetails.csv', encoding='unicode_escape')
employee_details.head()

# Implot to show relationship between features
sns.lmplot(x='Years', y='Compensation', data=employee_details, aspect=2)
plt.title('Relationship between Employee Tenure and Compensation')
plt.xlabel('Years Worked')
plt.ylabel('Compensation')
plt.grid(True)
plt.show()

"""### Findings
The scatter plot showcases the diversity in compensation among employees with varying years of service. Without asserting any obvious connection between years worked and salary progression.

"""

